### PR TITLE
Fix inclusion of system provided status code

### LINKED ISSUE #268: Errors with non-embedded status code
When setting `OUTCOME_BUNDLE_EMBEDDED_STATUS_CODE` to `OFF`, `find_quickcpplib_library` complains that no `project()` has been called. So this has to be moved further down (not sure if `ensure_git_subrepo` can be moved too).

`include/outcome/experimental/status_result.hpp` also received knowledge about whether system or embedded status code is used to include `system_error2.hpp`. This logic is missing in `coroutine_support.hpp` when including status code's `system_code_from_exception.hpp`.

The only other thing that then fails with vcpkg is that status code headers are put into a `status-code` directory which is missing in its `INTERFACE_SOURCES`.

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
These popped up while intergrating with vcpkg, see commit messages. Fixes #268

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
@ned14 this is ready for review now.

File: include/outcome/experimental/coroutine_support.hpp [hunk 1]
```diff
@@ -45,7 +45,11 @@ Distributed under the Boost Software License, Version 1.0.
   OUTCOME_V2_NAMESPACE_END
 
 #ifdef __cpp_exceptions
+#if !OUTCOME_USE_SYSTEM_STATUS_CODE && __has_include("status-code/include/system_code_from_exception.hpp")
```
Comment (ned14) [inline include/outcome/experimental/coroutine_support.hpp:48]: Path correct?

**Review by ned14 — CHANGES_REQUESTED** [review]

File: include/outcome/experimental/coroutine_support.hpp (hunk 1 above)
Comment (BurningEnlightenment) [reply include/outcome/experimental/coroutine_support.hpp]: Whoops, fixed.

**Review by ned14 — APPROVED** [review]
